sudo: required
services:
  - docker

before_install:
  - docker build -t awijaya/docker-practice-react -f Dockerfile.dev .

script:
  - docker run awijaya/docker-practice-react npm run test -- --coverage