sudo: required
services:
  - docker

before_install:
  - docker build -t awijaya/docker-practice-react -f Dockerfile.dev .

script:
  - docker run awijaya/docker-practice-react npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "ap-southeast-1"
  app: "docker-react-testing"
  env: "DockerReactTesting-env"
  bucket_name: "elasticbeanstalk-ap-southeast-1-283029111940"
  bucket_path: "docker-react-testing"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY"